In [4]:
import pandas as pd
import numpy as np

import seaborn; seaborn.set()
import matplotlib.pyplot as plt

from datetime import datetime

%matplotlib inline

In [5]:
location = "datasets/DC_Properties.csv"
df_properties = pd.read_csv(location)
df_properties

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
5,5,3,2,Hot Water Rad,Y,1.0,10,5,1913.0,NaN,...,-77.039715,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
6,6,1,0,Warm Cool,Y,2.0,5,2,1917.0,1988.0,...,-77.041055,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
7,7,3,1,Hot Water Rad,Y,2.0,8,4,1906.0,2011.0,...,-77.040129,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
8,8,3,1,Warm Cool,Y,2.0,7,3,1908.0,2008.0,...,-77.039903,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
9,9,1,1,Hot Water Rad,Y,1.0,6,2,1908.0,1979.0,...,-77.040081,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
10,10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,...,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
11,11,5,0,Hot Water Rad,Y,3.0,16,6,1905.0,NaN,...,-77.039718,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
12,12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,...,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
13,13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,...,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
14,14,3,1,Warm Cool,Y,2.0,5,3,1917.0,2000.0,...,-77.039716,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
15,15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,...,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
16,16,3,1,Warm Cool,Y,1.0,8,3,1908.0,2006.0,...,-77.039844,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
17,17,2,0,Hot Water Rad,N,1.0,6,3,1908.0,1987.0,...,-77.039961,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
18,18,3,1,Hot Water Rad,Y,2.0,10,4,1908.0,2006.0,...,-77.040020,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
19,19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
20,20,3,1,Hot Water Rad,Y,1.0,14,5,1880.0,2009.0,...,-77.033774,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
21,21,3,0,Forced Air,Y,2.0,12,3,1880.0,2009.0,...,-77.033838,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
22,22,1,0,Forced Air,Y,1.0,6,3,1880.0,2010.0,...,-77.033925,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
23,23,2,1,Forced Air,Y,1.0,5,3,1880.0,2010.0,...,-77.033972,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
24,24,2,1,Hot Water Rad,Y,1.0,8,3,1880.0,2004.0,...,-77.034070,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
25,25,1,0,Hot Water Rad,N,1.0,8,4,1880.0,2010.0,...,-77.034156,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
26,26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,...,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
27,27,3,0,Hot Water Rad,Y,4.0,9,3,1900.0,1963.0,...,-77.034182,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
28,28,3,0,Warm Cool,Y,2.0,10,4,1900.0,1960.0,...,-77.034119,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
29,29,3,1,Forced Air,Y,2.0,11,3,1900.0,2014.0,...,-77.034051,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158927,158927,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158928,158928,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158929,158929,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158930,158930,2,0,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158931,158931,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158932,158932,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158933,158933,2,0,Ht Pump,Y,NaN,4,2,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158934,158934,1,1,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158935,158935,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158936,158936,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158937,158937,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158938,158938,2,0,Warm Cool,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158939,158939,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158940,158940,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158941,158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158943,158943,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158944,158944,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158945,158945,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158946,158946,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158947,158947,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158948,158948,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158949,158949,1,1,Forced Air,Y,NaN,4,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158950,158950,3,0,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158951,158951,3,1,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158952,158952,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158953,158953,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158955,158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [6]:
df_properties.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [7]:
#we want to look at all of the rows with missing data in any column

df_properties.count()

Unnamed: 0            158957
BATHRM                158957
HF_BATHRM             158957
HEAT                  158957
AC                    158957
NUM_UNITS             106696
ROOMS                 158957
BEDRM                 158957
AYB                   158686
YR_RMDL                80928
EYB                   158957
STORIES               106652
SALEDATE              132187
PRICE                  98216
QUALIFIED             158957
SALE_NUM              158957
GBA                   106696
BLDG_NUM              158957
STYLE                 106696
STRUCT                106696
GRADE                 106696
CNDTN                 106696
EXTWALL               106696
ROOF                  106696
INTWALL               106696
KITCHENS              106695
FIREPLACES            158957
USECODE               158957
LANDAREA              158957
GIS_LAST_MOD_DTTM     158957
SOURCE                158957
CMPLX_NUM              52261
LIVING_GBA             52261
FULLADDRESS           106040
CITY                  106051
STATE                 106051
ZIPCODE               158956
NATIONALGRID          106051
LATITUDE              158956
LONGITUDE             158956
ASSESSMENT_NBHD       158956
ASSESSMENT_SUBNBHD    126406
CENSUS_TRACT          158956
CENSUS_BLOCK          106051
WARD                  158956
SQUARE                158957
X                     158720
Y                     158720
QUADRANT              158720
dtype: int64

In [8]:
#return counts of rows for which there are missing values, set as new data frame
df_properties_missing = df_properties.isnull().sum()

In [9]:
#sort these counts in descending order
#df_properties_missing.sort_values(ascending=False)

In [10]:
#isolate properties with 3 bedrooms
df_3BED = df_properties.where(df_properties['BEDRM']==3)

In [11]:
#find median property price
medprice = df_3BED['PRICE'].median()
medprice

390000.0

In [12]:
#Look at the average remodel year for properties that sold below median price
df_below = df_3BED.where(df_properties['PRICE']< medprice)

In [13]:
modeYR_RMDL = df_below['YR_RMDL'].mode()
modeYR_RMDL

0    2011.0
dtype: float64

In [14]:
#look at this subset of data (houses with 3 bedrooms that sold below median price) sorted by the Census block
df_below.sort_values(by='CENSUS_BLOCK')

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
21294,21294.0,1.0,1.0,Hot Water Rad,N,1.0,6.0,3.0,1900.0,1954.0,...,-77.060353,Georgetown,025 F Georgetown,100.0,000100 1003,Ward 2,1282,-77.060462,38.911769,NW
21291,21291.0,2.0,1.0,Warm Cool,Y,1.0,6.0,3.0,1909.0,1987.0,...,-77.060727,Georgetown,025 F Georgetown,100.0,000100 1003,Ward 2,1282,-77.060462,38.911769,NW
23949,23949.0,1.0,1.0,Warm Cool,Y,1.0,5.0,3.0,1940.0,2002.0,...,-77.063955,Georgetown,025 F Georgetown,100.0,000100 1006,Ward 2,1280,-77.064610,38.911993,NW
22504,22504.0,2.0,1.0,Warm Cool,Y,1.0,6.0,3.0,1940.0,1986.0,...,-77.055183,Georgetown,025 J Georgetown,100.0,000100 2003,Ward 2,1262,-77.055440,38.908912,NW
22503,22503.0,1.0,0.0,Hot Water Rad,N,1.0,5.0,3.0,1941.0,NaN,...,-77.055701,Georgetown,025 J Georgetown,100.0,000100 2003,Ward 2,1262,-77.055440,38.908912,NW
22216,22216.0,1.0,0.0,Hot Water Rad,N,1.0,6.0,3.0,1900.0,NaN,...,-77.056880,Georgetown,025 J Georgetown,100.0,000100 2006,Ward 2,1215,-77.056279,38.906508,NW
20745,20745.0,2.0,2.0,Hot Water Rad,N,1.0,7.0,3.0,1900.0,2013.0,...,-77.056873,Georgetown,025 J Georgetown,100.0,000100 2008,Ward 2,1239,-77.056595,38.908099,NW
18568,18568.0,2.0,1.0,Hot Water Rad,N,2.0,8.0,3.0,1890.0,2009.0,...,-77.059889,Georgetown,025 F Georgetown,100.0,000100 3002,Ward 2,1269,-77.060458,38.909944,NW
20160,20160.0,2.0,1.0,Warm Cool,Y,1.0,6.0,3.0,1942.0,NaN,...,-77.062117,Georgetown,025 F Georgetown,100.0,000100 3003,Ward 2,1270,-77.062651,38.909990,NW
21322,21322.0,2.0,1.0,Hot Water Rad,N,1.0,9.0,3.0,1900.0,2014.0,...,-77.057290,Georgetown,025 J Georgetown,100.0,000100 3009,Ward 2,1240,-77.057496,38.907986,NW
22360,22360.0,2.0,0.0,Hot Water Rad,N,2.0,10.0,3.0,1900.0,1990.0,...,-77.063041,Georgetown,025 G Georgetown,100.0,000100 3012,Ward 2,1243,-77.062861,38.908212,NW
22191,22191.0,2.0,1.0,Warm Cool,Y,1.0,6.0,3.0,1900.0,1977.0,...,-77.057201,Georgetown,025 J Georgetown,100.0,000100 4007,Ward 2,1213,-77.057451,38.906405,NW
21249,21249.0,3.0,1.0,Warm Cool,Y,1.0,7.0,3.0,1900.0,NaN,...,-77.066644,Georgetown,025 D Georgetown,202.0,000202 1006,Ward 2,1290,-77.066994,38.912203,NW
21244,21244.0,2.0,0.0,Hot Water Rad,N,2.0,6.0,3.0,1915.0,NaN,...,-77.066323,Georgetown,025 D Georgetown,202.0,000202 1006,Ward 2,1290,-77.066994,38.912203,NW
21706,21706.0,2.0,1.0,Warm Cool,Y,1.0,8.0,3.0,1900.0,NaN,...,-77.066333,Georgetown,025 D Georgetown,202.0,000202 1006,Ward 2,1290,-77.066994,38.912203,NW
19332,19332.0,1.0,0.0,Warm Cool,Y,1.0,6.0,3.0,1936.0,1985.0,...,-77.066291,Georgetown,025 D Georgetown,202.0,000202 1008,Ward 2,1278,-77.066835,38.911276,NW
19325,19325.0,3.0,1.0,Warm Cool,Y,1.0,7.0,3.0,1912.0,1974.0,...,-77.066600,Georgetown,025 D Georgetown,202.0,000202 1008,Ward 2,1278,-77.066835,38.911276,NW
20299,20299.0,1.0,1.0,Warm Cool,Y,1.0,7.0,3.0,1900.0,1956.0,...,-77.065925,Georgetown,025 D Georgetown,202.0,000202 2000,Ward 2,1272,-77.065665,38.910300,NW
18456,18456.0,2.0,1.0,Warm Cool,Y,1.0,6.0,3.0,1900.0,1999.0,...,-77.065921,Georgetown,025 D Georgetown,202.0,000202 2000,Ward 2,1272,-77.065665,38.910300,NW
18441,18441.0,1.0,1.0,Hot Water Rad,N,1.0,6.0,3.0,1900.0,NaN,...,-77.065715,Georgetown,025 D Georgetown,202.0,000202 2000,Ward 2,1272,-77.065665,38.910300,NW
18115,18115.0,1.0,1.0,Hot Water Rad,N,1.0,6.0,3.0,1900.0,1940.0,...,-77.068006,Georgetown,025 D Georgetown,202.0,000202 2002,Ward 2,1274,-77.068335,38.910213,NW
20296,20296.0,1.0,1.0,Hot Water Rad,N,1.0,6.0,3.0,1900.0,1942.0,...,-77.068009,Georgetown,025 D Georgetown,202.0,000202 2002,Ward 2,1274,-77.068335,38.910213,NW
18741,18741.0,2.0,1.0,Warm Cool,Y,1.0,6.0,3.0,1941.0,1941.0,...,-77.068688,Georgetown,025 D Georgetown,202.0,000202 2002,Ward 2,1274,-77.068335,38.910213,NW
20218,20218.0,2.0,1.0,Hot Water Rad,N,1.0,6.0,3.0,1900.0,1966.0,...,-77.068825,Georgetown,025 D Georgetown,202.0,000202 2003,Ward 2,1253,-77.068078,38.909238,NW
18989,18989.0,2.0,0.0,Forced Air,N,1.0,5.0,3.0,1900.0,1973.0,...,-77.066285,Georgetown,025 D Georgetown,202.0,000202 2004,Ward 2,1254,-77.066978,38.909319,NW
19242,19242.0,2.0,0.0,Hot Water Rad,N,1.0,8.0,3.0,1900.0,1980.0,...,-77.065848,Georgetown,025 E Georgetown,202.0,000202 2006,Ward 2,1244,-77.064753,38.908358,NW
19556,19556.0,4.0,1.0,Warm Cool,Y,1.0,9.0,3.0,1830.0,2007.0,...,-77.067668,Georgetown,025 E Georgetown,202.0,000202 3005,Ward 2,1220,-77.067246,38.906357,NW
19093,19093.0,3.0,1.0,Warm Cool,Y,1.0,7.0,3.0,1900.0,1976.0,...,-77.065390,Georgetown,025 E Georgetown,202.0,000202 3006,Ward 2,1219,-77.065714,38.906361,NW
19872,19872.0,3.0,0.0,Warm Cool,Y,2.0,8.0,3.0,1900.0,1979.0,...,-77.065904,Georgetown,025 E Georgetown,202.0,000202 3010,Ward 2,1206,-77.065625,38.905531,NW
19749,19749.0,3.0,0.0,Hot Water Rad,N,3.0,9.0,3.0,1900.0,NaN,...,-77.066169,Georgetown,025 E Georgetown,202.0,000202 3011,Ward 2,1205,-77.066926,38.905624,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158935,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158951,158951.0,3.0,1.0,Forced Air,Y,NaN,5.0,3.0,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158953,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#look at the median sales price by census block
df_lowpriceblocks = df_below['PRICE'].groupby(df_below['CENSUS_BLOCK']).median()
df_lowpriceblocks

CENSUS_BLOCK
000100 1003    377500.0
000100 1006    289500.0
000100 2003    354500.0
000100 2006    340000.0
000100 2008    330000.0
000100 3002        10.0
000100 3003    378000.0
000100 3009    325000.0
000100 3012    235000.0
000100 4007    250000.0
000202 1006    266000.0
000202 1008    302500.0
000202 2000    357000.0
000202 2002    365000.0
000202 2003    372500.0
000202 2004    355000.0
000202 2006    294500.0
000202 3005     51000.0
000202 3006    320000.0
000202 3010    225000.0
000202 3011    365000.0
000202 3012    230000.0
000202 3013    310000.0
000202 4003    291000.0
000202 4004    246000.0
000300 1000    382000.0
000300 1001    340000.0
000300 1003    223000.0
000300 1004    275000.0
000300 1005    184000.0
                 ...
011100 2010    357512.5
011100 2012    160000.0
011100 2014    230000.0
011100 2015     75000.0
011100 2016    153350.0
011100 2017    160000.0
011100 2019    284000.0
011100 2020    274900.0
011100 2021    256500.0
011100 2022    146500.0
011100 2023    141250.0
011100 2025    240000.0
011100 2026    215000.0
011100 2027    246900.0
011100 2028    200000.0
011100 2029    168000.0
011100 2030    167000.0
011100 3001    175000.0
011100 3002    180000.0
011100 3003    325000.0
011100 3004    310000.0
011100 3005    127750.0
011100 3006    305900.0
011100 3007    170000.0
011100 3011     63500.0
011100 3037    300000.0
011100 3038     89500.0
011100 3039    225000.0
011100 3040     75000.0
011100 3041    230000.0
Name: PRICE, Length: 2729, dtype: float64

In [16]:
df_lowpriceblocks.columns = ['Median Price']

In [17]:
df_lowpriceblocks

CENSUS_BLOCK
000100 1003    377500.0
000100 1006    289500.0
000100 2003    354500.0
000100 2006    340000.0
000100 2008    330000.0
000100 3002        10.0
000100 3003    378000.0
000100 3009    325000.0
000100 3012    235000.0
000100 4007    250000.0
000202 1006    266000.0
000202 1008    302500.0
000202 2000    357000.0
000202 2002    365000.0
000202 2003    372500.0
000202 2004    355000.0
000202 2006    294500.0
000202 3005     51000.0
000202 3006    320000.0
000202 3010    225000.0
000202 3011    365000.0
000202 3012    230000.0
000202 3013    310000.0
000202 4003    291000.0
000202 4004    246000.0
000300 1000    382000.0
000300 1001    340000.0
000300 1003    223000.0
000300 1004    275000.0
000300 1005    184000.0
                 ...
011100 2010    357512.5
011100 2012    160000.0
011100 2014    230000.0
011100 2015     75000.0
011100 2016    153350.0
011100 2017    160000.0
011100 2019    284000.0
011100 2020    274900.0
011100 2021    256500.0
011100 2022    146500.0
011100 2023    141250.0
011100 2025    240000.0
011100 2026    215000.0
011100 2027    246900.0
011100 2028    200000.0
011100 2029    168000.0
011100 2030    167000.0
011100 3001    175000.0
011100 3002    180000.0
011100 3003    325000.0
011100 3004    310000.0
011100 3005    127750.0
011100 3006    305900.0
011100 3007    170000.0
011100 3011     63500.0
011100 3037    300000.0
011100 3038     89500.0
011100 3039    225000.0
011100 3040     75000.0
011100 3041    230000.0
Name: PRICE, Length: 2729, dtype: float64

In [18]:
lowpricedf = pd.DataFrame(data=df_lowpriceblocks)

In [19]:
lowpricedf.head()

                 PRICE
CENSUS_BLOCK
000100 1003   377500.0
000100 1006   289500.0
000100 2003   354500.0
000100 2006   340000.0
000100 2008   330000.0

In [20]:
lowpricedf.columns = ['Median Price']
lowpricedf.head()

              Median Price
CENSUS_BLOCK
000100 1003       377500.0
000100 1006       289500.0
000100 2003       354500.0
000100 2006       340000.0
000100 2008       330000.0

In [21]:
lowpricedf.reset_index(level=0, inplace=True)
lowpricedf.head()

  CENSUS_BLOCK  Median Price
0  000100 1003      377500.0
1  000100 1006      289500.0
2  000100 2003      354500.0
3  000100 2006      340000.0
4  000100 2008      330000.0

In [22]:
lowpricedf.columns = ['Census Block','Median Price']
lowpricedf.head()

  Census Block  Median Price
0  000100 1003      377500.0
1  000100 1006      289500.0
2  000100 2003      354500.0
3  000100 2006      340000.0
4  000100 2008      330000.0

In [23]:
df_threebedpricebyward = pd.DataFrame(data=threebedpricebyward)
df_threebedpricebyward.head()

NameError: name 'threebedpricebyward' is not defined

In [24]:
#In the 3 bedroom dataset (df_3BED), remove rows with missing Price and Year Remodel Data
df_3BED_nomissing = df_3BED.dropna(subset = ['PRICE','YR_RMDL'])
df_3BED_nomissing.count()

Unnamed: 0            15127
BATHRM                15127
HF_BATHRM             15127
HEAT                  15127
AC                    15127
NUM_UNITS             13936
ROOMS                 15127
BEDRM                 15127
AYB                   15108
YR_RMDL               15127
EYB                   15127
STORIES               13936
SALEDATE              15127
PRICE                 15127
QUALIFIED             15127
SALE_NUM              15127
GBA                   13936
BLDG_NUM              15127
STYLE                 13936
STRUCT                13936
GRADE                 13936
CNDTN                 13936
EXTWALL               13936
ROOF                  13936
INTWALL               13936
KITCHENS              13936
FIREPLACES            15127
USECODE               15127
LANDAREA              15127
GIS_LAST_MOD_DTTM     15127
SOURCE                15127
CMPLX_NUM              1191
LIVING_GBA             1191
FULLADDRESS           13890
CITY                  13890
STATE                 13890
ZIPCODE               15127
NATIONALGRID          13890
LATITUDE              15127
LONGITUDE             15127
ASSESSMENT_NBHD       15127
ASSESSMENT_SUBNBHD    13411
CENSUS_TRACT          15127
CENSUS_BLOCK          13890
WARD                  15127
SQUARE                15127
X                     15104
Y                     15104
QUADRANT              15104
dtype: int64

In [25]:
#look at the subset of data of houses with 3 bedrooms; group the price and the year remodel by ward
df_3BEDBYWARD = df_3BED_nomissing[['PRICE','YR_RMDL']].groupby(df_3BED_nomissing['WARD']).median()
df_3BEDBYWARD.head()

            PRICE  YR_RMDL
WARD
Ward 1   610000.0   2008.0
Ward 2  1000000.0   2004.0
Ward 3   785000.0   2003.0
Ward 4   490000.0   2010.0
Ward 5   405000.0   2009.0

In [ ]:
#Isolate house information, look at just the EYB, AYB, YR_RMDL

In [26]:
df_properties_timebuilt = df_properties[['AYB','EYB','YR_RMDL']]
df_properties_timebuilt.head()

      AYB   EYB  YR_RMDL
0  1910.0  1972   1988.0
1  1898.0  1972   2007.0
2  1910.0  1984   2009.0
3  1900.0  1984   2003.0
4  1913.0  1985   2012.0

In [27]:
#round the years to an integer
df_properties_timebuilt = df_properties_timebuilt.round(0)
df_properties_timebuilt.head()

      AYB   EYB  YR_RMDL
0  1910.0  1972   1988.0
1  1898.0  1972   2007.0
2  1910.0  1984   2009.0
3  1900.0  1984   2003.0
4  1913.0  1985   2012.0

In [28]:
# now I want to remove any rows with missing year information
df_properties_timebuilt_nomissing = df_properties_timebuilt.dropna()


# now I want to convert the years, which are floats, to integers
df_properties_years = df_properties_timebuilt_nomissing.astype('int64')
df_properties_years.head()

    AYB   EYB  YR_RMDL
0  1910  1972     1988
1  1898  1972     2007
2  1910  1984     2009
3  1900  1984     2003
4  1913  1985     2012

In [36]:
#add a column that gives the time delta showing the length of time between the current year
#and the last remodel

df_properties_years = pd.to_datetime(df_properties_years, format = '%Y')
df_properties_years.head()

ValueError: to assemble mappings requires at least that [year, month, day] be specified: [day,month,year] is missing